/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm.softwaretestproject;


import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class ClerkMainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public ClerkMainWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
        AccSearchOperations.fillTable(jTable1, "", sortByArg());
        setFieldAccSummary();
    }
    
    public void setFieldAccSummary(){
        int totAcc = getAccInfo("total");
        int totSav = getAccInfo("saving");
        int totCred = getAccInfo("credit");
        int totCheck = getAccInfo("checking");
        jTextField_totAcc.setText(Integer.toString(totAcc));
        jTextField_totSaving.setText(Integer.toString(totSav));
        jTextField_totCredit.setText(Integer.toString(totCred));
        jTextField_totChecking.setText(Integer.toString(totCheck));
        
        double totBal = getBalanceInfo("total");
        double avgBal = getBalanceInfo("avg");
        jTextField_totBalance.setText(Double.toString(totBal));
        String avgBal3DecPoints = String.format("%.3f", avgBal);
        jTextField_AvgBalance.setText(avgBal3DecPoints);
    }
    
    public int getAccInfo(String operation){
        PreparedStatement st;
        ResultSet rs;
        int out = 0;
        
        String query = "SELECT * FROM users WHERE id>1";
        int total=0, saving=0, credit=0,checking=0;
        try{
            st = DerbyConn.getConnection().prepareStatement(query);
            rs = st.executeQuery();
            
            while(rs.next()){
                total++;
//                String accType = rs.getString("accType");
//                System.out.println(accType);
//                System.out.println();
                if((rs.getString("accType")).equals("Saving Account")){
                    saving++;
                }else if(rs.getString("accType").equals("Credit Account")){
                    credit++;
                }else{
                    checking++;
                }
            }
            switch(operation){
                case "total": out = total; break;
                case "saving": out = saving; break;
                case "credit": out = credit; break;
                case "checking": out = checking; break;
            }
        }catch (SQLException ex) {
//            Logger.getLogger(LoginWindow.class.getName()).log(Level.SEVERE, null, ex);
              System.out.println(ex);
              JOptionPane.showMessageDialog(null, ex,"Get Info Error",2);
        }
        
        return out;
    }
    
    public double getBalanceInfo(String operation){
        PreparedStatement st;
        ResultSet rs;
        double out = 0;
        
        String query = "SELECT * FROM users WHERE id>1";
        
        double totalBalance=0, totalAcc=0;
        double avg=0;

        try{
            st = DerbyConn.getConnection().prepareStatement(query);
            rs = st.executeQuery();
            
            while(rs.next()){
                totalAcc++;
                totalBalance += rs.getDouble("balance");
            }
            avg = totalBalance/totalAcc;
            switch(operation){
                case "total": out = totalBalance; break;
                case "avg": out = avg; break;
            }
        }catch (SQLException ex) {
//            Logger.getLogger(LoginWindow.class.getName()).log(Level.SEVERE, null, ex);
              System.out.println(ex);
              JOptionPane.showMessageDialog(null, ex,"Get Info Error",2);
        }
        
        return out;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JLabel();
        summaryTabTemp = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jTextField_totSaving1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextField_totCredit1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextField_totChecking1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        createAccPanel = new javax.swing.JPanel();
        PIN_Panel = new javax.swing.JPanel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        ConfPIN_Panel = new javax.swing.JPanel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        NamePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Name = new javax.swing.JTextField();
        APY_CreditLine_Transfee_Panel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_accType = new javax.swing.JTextField();
        AccType_Panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        DepositPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_deposit = new javax.swing.JTextField();
        ResetBtn = new javax.swing.JButton();
        RegBtn = new javax.swing.JButton();
        SearchAccountsPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        sortByComboBox = new javax.swing.JComboBox<>();
        filterBtn = new javax.swing.JLabel();
        filterBtn.setVisible(false);
        jLabel26 = new javax.swing.JLabel();
        jTextField_searchKey = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        accInfoPanel = new javax.swing.JPanel();
        AllSummaryTab = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jTextField_totAcc = new javax.swing.JTextField();
        jTextField_totSaving = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField_totCredit = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField_totChecking = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jTextField_totBalance = new javax.swing.JTextField();
        jTextField_AvgBalance = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel11.setText("jLabel11");

        searchBtn.setBackground(new java.awt.Color(255, 255, 255));
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/softwaretestproject/imgs/search.png"))); // NOI18N
        searchBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel31.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 78, 152));
        jLabel31.setText("Average: ");

        jTextField_totSaving1.setEditable(false);
        jTextField_totSaving1.setBackground(new java.awt.Color(102, 102, 102));
        jTextField_totSaving1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jTextField_totSaving1.setForeground(new java.awt.Color(212, 255, 255));
        jTextField_totSaving1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_totSaving1.setText("");
        jTextField_totSaving1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_totSaving1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_totSaving1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_totSaving1FocusLost(evt);
            }
        });
        jTextField_totSaving1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_totSaving1ActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 78, 152));
        jLabel32.setText("Credit Accounts : ");

        jTextField_totCredit1.setEditable(false);
        jTextField_totCredit1.setBackground(new java.awt.Color(102, 102, 102));
        jTextField_totCredit1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jTextField_totCredit1.setForeground(new java.awt.Color(241, 224, 255));
        jTextField_totCredit1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_totCredit1.setText("");
        jTextField_totCredit1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_totCredit1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_totCredit1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_totCredit1FocusLost(evt);
            }
        });
        jTextField_totCredit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_totCredit1ActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 78, 152));
        jLabel33.setText("Checking Accounts: ");

        jTextField_totChecking1.setEditable(false);
        jTextField_totChecking1.setBackground(new java.awt.Color(102, 102, 102));
        jTextField_totChecking1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jTextField_totChecking1.setForeground(new java.awt.Color(204, 255, 204));
        jTextField_totChecking1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_totChecking1.setText("");
        jTextField_totChecking1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_totChecking1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_totChecking1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_totChecking1FocusLost(evt);
            }
        });
        jTextField_totChecking1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_totChecking1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout summaryTabTempLayout = new javax.swing.GroupLayout(summaryTabTemp);
        summaryTabTemp.setLayout(summaryTabTempLayout);
        summaryTabTempLayout.setHorizontalGroup(
            summaryTabTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(summaryTabTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(summaryTabTempLayout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addGroup(summaryTabTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, summaryTabTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, summaryTabTempLayout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_totChecking1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, summaryTabTempLayout.createSequentialGroup()
                                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_totCredit1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(summaryTabTempLayout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(jLabel31)
                            .addGap(133, 133, 133)
                            .addComponent(jTextField_totSaving1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(9, 9, 9)))
        );
        summaryTabTempLayout.setVerticalGroup(
            summaryTabTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
            .addGroup(summaryTabTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(summaryTabTempLayout.createSequentialGroup()
                    .addGap(125, 125, 125)
                    .addGroup(summaryTabTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_totSaving1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(summaryTabTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_totCredit1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(summaryTabTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_totChecking1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(173, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/atm/softwaretestproject/imgs/bank.png")).getImage());
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Clerk's Main Window");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/softwaretestproject/imgs/logout.png"))); // NOI18N
        jLabel2.setText("Log out");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        createAccPanel.setBackground(new java.awt.Color(255, 255, 255));
        createAccPanel.setPreferredSize(new java.awt.Dimension(515, 500));

        PIN_Panel.setBackground(new java.awt.Color(255, 255, 255));

        jPasswordField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(204, 152, 140));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(66, 157, 165)));
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });

        jLabel3.setText("PIN (6-digit number):");

        javax.swing.GroupLayout PIN_PanelLayout = new javax.swing.GroupLayout(PIN_Panel);
        PIN_Panel.setLayout(PIN_PanelLayout);
        PIN_PanelLayout.setHorizontalGroup(
            PIN_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PIN_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PIN_PanelLayout.setVerticalGroup(
            PIN_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PIN_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PIN_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ConfPIN_Panel.setBackground(new java.awt.Color(255, 255, 255));

        jPasswordField2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(204, 152, 140));
        jPasswordField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(66, 157, 165)));
        jPasswordField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusLost(evt);
            }
        });
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyPressed(evt);
            }
        });

        jLabel4.setText("Confirm PIN:");

        javax.swing.GroupLayout ConfPIN_PanelLayout = new javax.swing.GroupLayout(ConfPIN_Panel);
        ConfPIN_Panel.setLayout(ConfPIN_PanelLayout);
        ConfPIN_PanelLayout.setHorizontalGroup(
            ConfPIN_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfPIN_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ConfPIN_PanelLayout.setVerticalGroup(
            ConfPIN_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfPIN_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConfPIN_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        NamePanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Name:");

        jTextField_Name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField_Name.setForeground(new java.awt.Color(204, 152, 140));
        jTextField_Name.setText("");
        jTextField_Name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(66, 157, 165)));
        jTextField_Name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_NameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_NameFocusLost(evt);
            }
        });
        jTextField_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NamePanelLayout = new javax.swing.GroupLayout(NamePanel);
        NamePanel.setLayout(NamePanelLayout);
        NamePanelLayout.setHorizontalGroup(
            NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        NamePanelLayout.setVerticalGroup(
            NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        APY_CreditLine_Transfee_Panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setText("Interest rate (% per Year): ");

        jTextField_accType.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField_accType.setForeground(new java.awt.Color(204, 152, 140));
        jTextField_accType.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(66, 157, 165)));
        jTextField_accType.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_accTypeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_accTypeFocusLost(evt);
            }
        });
        jTextField_accType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_accTypeActionPerformed(evt);
            }
        });
        jTextField_accType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_accTypeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_accTypeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout APY_CreditLine_Transfee_PanelLayout = new javax.swing.GroupLayout(APY_CreditLine_Transfee_Panel);
        APY_CreditLine_Transfee_Panel.setLayout(APY_CreditLine_Transfee_PanelLayout);
        APY_CreditLine_Transfee_PanelLayout.setHorizontalGroup(
            APY_CreditLine_Transfee_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(APY_CreditLine_Transfee_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jTextField_accType, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        APY_CreditLine_Transfee_PanelLayout.setVerticalGroup(
            APY_CreditLine_Transfee_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(APY_CreditLine_Transfee_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(APY_CreditLine_Transfee_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_accType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        AccType_Panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Account Type: ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saving Account", "Credit Account", "Checking Account" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AccType_PanelLayout = new javax.swing.GroupLayout(AccType_Panel);
        AccType_Panel.setLayout(AccType_PanelLayout);
        AccType_PanelLayout.setHorizontalGroup(
            AccType_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccType_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        AccType_PanelLayout.setVerticalGroup(
            AccType_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccType_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AccType_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        DepositPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Deposit : ");

        jTextField_deposit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField_deposit.setForeground(new java.awt.Color(204, 152, 140));
        jTextField_deposit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(66, 157, 165)));
        jTextField_deposit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_depositFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_depositFocusLost(evt);
            }
        });
        jTextField_deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_depositActionPerformed(evt);
            }
        });
        jTextField_deposit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_depositKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_depositKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout DepositPanelLayout = new javax.swing.GroupLayout(DepositPanel);
        DepositPanel.setLayout(DepositPanelLayout);
        DepositPanelLayout.setHorizontalGroup(
            DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepositPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField_deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        DepositPanelLayout.setVerticalGroup(
            DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepositPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_deposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ResetBtn.setBackground(new java.awt.Color(24, 27, 112));
        ResetBtn.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        ResetBtn.setForeground(new java.awt.Color(255, 255, 255));
        ResetBtn.setText("Reset");
        ResetBtn.setBorder(null);
        ResetBtn.setBorderPainted(false);
        ResetBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ResetBtn.setMaximumSize(new java.awt.Dimension(95, 33));
        ResetBtn.setMinimumSize(new java.awt.Dimension(95, 33));
        ResetBtn.setPreferredSize(new java.awt.Dimension(95, 33));
        ResetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetBtnMouseClicked(evt);
            }
        });
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });

        RegBtn.setBackground(new java.awt.Color(24, 27, 112));
        RegBtn.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        RegBtn.setForeground(new java.awt.Color(255, 255, 255));
        RegBtn.setText("Add Account");
        RegBtn.setBorder(null);
        RegBtn.setBorderPainted(false);
        RegBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegBtnMouseClicked(evt);
            }
        });
        RegBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createAccPanelLayout = new javax.swing.GroupLayout(createAccPanel);
        createAccPanel.setLayout(createAccPanelLayout);
        createAccPanelLayout.setHorizontalGroup(
            createAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAccPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(createAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DepositPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AccType_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(APY_CreditLine_Transfee_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(createAccPanelLayout.createSequentialGroup()
                        .addGroup(createAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(createAccPanelLayout.createSequentialGroup()
                                .addComponent(ResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RegBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ConfPIN_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PIN_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NamePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(42, 42, 42))
        );
        createAccPanelLayout.setVerticalGroup(
            createAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAccPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(PIN_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConfPIN_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AccType_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(APY_CreditLine_Transfee_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DepositPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(createAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        jTabbedPane1.addTab("Create Account", createAccPanel);

        SearchAccountsPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel12.setText("Sort by:");

        sortByComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Account Number", "Name", "Balance", "Account Type", "Creation Date" }));
        sortByComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByComboBoxActionPerformed(evt);
            }
        });

        filterBtn.setBackground(new java.awt.Color(255, 255, 255));
        filterBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/softwaretestproject/imgs/filter.png"))); // NOI18N
        filterBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filterBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filterBtnMouseClicked(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel26.setText("Search by name:");

        jTextField_searchKey.setBackground(new java.awt.Color(102, 102, 102));
        jTextField_searchKey.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField_searchKey.setForeground(new java.awt.Color(255, 255, 204));
        jTextField_searchKey.setText("");
        jTextField_searchKey.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_searchKey.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_searchKeyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_searchKeyFocusLost(evt);
            }
        });
        jTextField_searchKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_searchKeyActionPerformed(evt);
            }
        });
        jTextField_searchKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_searchKeyKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_searchKeyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_searchKeyKeyTyped(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account Number", "Name", "Balance", "Account Type", "Creation Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout SearchAccountsPanelLayout = new javax.swing.GroupLayout(SearchAccountsPanel);
        SearchAccountsPanel.setLayout(SearchAccountsPanelLayout);
        SearchAccountsPanelLayout.setHorizontalGroup(
            SearchAccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchAccountsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_searchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SearchAccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sortByComboBox, 0, 0, Short.MAX_VALUE)
                    .addGroup(SearchAccountsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );
        SearchAccountsPanelLayout.setVerticalGroup(
            SearchAccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchAccountsPanelLayout.createSequentialGroup()
                .addGroup(SearchAccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchAccountsPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(SearchAccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(SearchAccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_searchKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(filterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(SearchAccountsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sortByComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Search Account", SearchAccountsPanel);
        SearchAccountsPanel.getAccessibleContext().setAccessibleName("");

        accInfoPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel25.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 78, 152));
        jLabel25.setText("Total number of accounts: ");

        jTextField_totAcc.setEditable(false);
        jTextField_totAcc.setBackground(new java.awt.Color(102, 102, 102));
        jTextField_totAcc.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jTextField_totAcc.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_totAcc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_totAcc.setText("");
        jTextField_totAcc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_totAcc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_totAccFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_totAccFocusLost(evt);
            }
        });
        jTextField_totAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_totAccActionPerformed(evt);
            }
        });

        jTextField_totSaving.setEditable(false);
        jTextField_totSaving.setBackground(new java.awt.Color(102, 102, 102));
        jTextField_totSaving.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jTextField_totSaving.setForeground(new java.awt.Color(212, 255, 255));
        jTextField_totSaving.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_totSaving.setText("");
        jTextField_totSaving.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_totSaving.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_totSavingFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_totSavingFocusLost(evt);
            }
        });
        jTextField_totSaving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_totSavingActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 78, 152));
        jLabel27.setText("Saving Accounts: ");

        jLabel28.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 78, 152));
        jLabel28.setText("Credit Accounts : ");

        jTextField_totCredit.setEditable(false);
        jTextField_totCredit.setBackground(new java.awt.Color(102, 102, 102));
        jTextField_totCredit.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jTextField_totCredit.setForeground(new java.awt.Color(241, 224, 255));
        jTextField_totCredit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_totCredit.setText("");
        jTextField_totCredit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_totCredit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_totCreditFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_totCreditFocusLost(evt);
            }
        });
        jTextField_totCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_totCreditActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 78, 152));
        jLabel29.setText("Checking Accounts: ");

        jTextField_totChecking.setEditable(false);
        jTextField_totChecking.setBackground(new java.awt.Color(102, 102, 102));
        jTextField_totChecking.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jTextField_totChecking.setForeground(new java.awt.Color(204, 255, 204));
        jTextField_totChecking.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_totChecking.setText("");
        jTextField_totChecking.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_totChecking.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_totCheckingFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_totCheckingFocusLost(evt);
            }
        });
        jTextField_totChecking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_totCheckingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel25))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jTextField_totAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_totSaving, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_totChecking, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_totCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_totAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_totSaving, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_totCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jTextField_totChecking, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );

        AllSummaryTab.addTab("Accounts", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel30.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 78, 152));
        jLabel30.setText("Total Balance: ");

        jTextField_totBalance.setEditable(false);
        jTextField_totBalance.setBackground(new java.awt.Color(102, 102, 102));
        jTextField_totBalance.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jTextField_totBalance.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_totBalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_totBalance.setText("");
        jTextField_totBalance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_totBalance.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_totBalanceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_totBalanceFocusLost(evt);
            }
        });
        jTextField_totBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_totBalanceActionPerformed(evt);
            }
        });

        jTextField_AvgBalance.setEditable(false);
        jTextField_AvgBalance.setBackground(new java.awt.Color(102, 102, 102));
        jTextField_AvgBalance.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jTextField_AvgBalance.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_AvgBalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_AvgBalance.setText("");
        jTextField_AvgBalance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_AvgBalance.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_AvgBalanceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_AvgBalanceFocusLost(evt);
            }
        });
        jTextField_AvgBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AvgBalanceActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 78, 152));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Average: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel30))
                    .addComponent(jTextField_AvgBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_totBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(130, 130, 130))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_totBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel34)
                .addGap(7, 7, 7)
                .addComponent(jTextField_AvgBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        AllSummaryTab.addTab("Balance", jPanel3);

        javax.swing.GroupLayout accInfoPanelLayout = new javax.swing.GroupLayout(accInfoPanel);
        accInfoPanel.setLayout(accInfoPanelLayout);
        accInfoPanelLayout.setHorizontalGroup(
            accInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AllSummaryTab, javax.swing.GroupLayout.PREFERRED_SIZE, 515, Short.MAX_VALUE)
        );
        accInfoPanelLayout.setVerticalGroup(
            accInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AllSummaryTab)
        );

        jTabbedPane1.addTab("Accounts Summary", accInfoPanel);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/softwaretestproject/imgs/cross (2).png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/softwaretestproject/imgs/minimize (1).png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(103, 103, 103)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(6, 6, 6))
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        LoginWindow form = new LoginWindow();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked
    Color darkBlue = new Color(66,157,165);
    Border jLabelBorderBef = BorderFactory.createMatteBorder(0, 0, 1, 0, darkBlue);
    Border jLabelBorderAft = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.red);
    private void jTextField_NameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_NameFocusGained
        jTextField_Name.setBorder(jLabelBorderAft);
    }//GEN-LAST:event_jTextField_NameFocusGained

    private void jTextField_NameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_NameFocusLost
        jTextField_Name.setBorder(jLabelBorderBef);
    }//GEN-LAST:event_jTextField_NameFocusLost

    private void jTextField_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NameActionPerformed

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        
        jPasswordField1.setBorder(jLabelBorderAft);
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        
        jPasswordField1.setBorder(jLabelBorderBef);
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
//        jPasswordField1.setEchoChar((char)0);
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jPasswordField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusGained
        // TODO add your handling code here:
        jPasswordField2.setBorder(jLabelBorderAft);
    }//GEN-LAST:event_jPasswordField2FocusGained

    private void jPasswordField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusLost
        // TODO add your handling code here:
        jPasswordField2.setBorder(jLabelBorderBef);
    }//GEN-LAST:event_jPasswordField2FocusLost

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jPasswordField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2KeyPressed

    private void jTextField_accTypeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_accTypeFocusGained
        // TODO add your handling code here:
        jTextField_accType.setBorder(jLabelBorderAft);
    }//GEN-LAST:event_jTextField_accTypeFocusGained

    private void jTextField_accTypeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_accTypeFocusLost
        // TODO add your handling code here:
        jTextField_accType.setBorder(jLabelBorderBef);
    }//GEN-LAST:event_jTextField_accTypeFocusLost

    private void jTextField_accTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_accTypeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField_accTypeActionPerformed

    private void RegBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegBtnActionPerformed
        
    }//GEN-LAST:event_RegBtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
//        if(jComboBox1.getSelectedItem()!=jLabel8.getText()){
//            jLabel8.setText(jComboBox1.getSelectedItem().toString());
//        }
        if(jComboBox1.getSelectedItem()=="Saving Account"){
            jLabel8.setText("Interest rate (% per Year): ");
        }else if(jComboBox1.getSelectedItem()=="Credit Account"){
            jLabel8.setText("Credit line:");
        }else{
            jLabel8.setText("Transaction fee:");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void ResetBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetBtnMouseClicked
        // TODO add your handling code here:
        reset();
        
    }//GEN-LAST:event_ResetBtnMouseClicked

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void jTextField_accTypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_accTypeKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField_accTypeKeyPressed

    private void RegBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegBtnMouseClicked
        // TODO add your handling code here:
//        String accNumb = jTextField_AccNumb.getText();
        String pin = String.valueOf(jPasswordField1.getPassword());
        String confPin = String.valueOf(jPasswordField2.getPassword());
        String name = jTextField_Name.getText();
        String acc = jTextField_accType.getText();
        String deposit = jTextField_deposit.getText();
        
        if(pin.equals("")){
            JOptionPane.showMessageDialog(null, "PIN field cannot be empty!", "Empty Field", 2);
        }else if(!pin.matches("\\d{6}")){
            JOptionPane.showMessageDialog(null, "PIN must be a 6-digit number", "Wrong length", 2);
        }else if(confPin.equals("")){
            JOptionPane.showMessageDialog(null, "Confirm PIN field cannot be empty!", "Empty Field", 2);
        }else if(!confPin.equals(pin)){
            JOptionPane.showMessageDialog(null, "The PIN and Confirmation PIN do not match", "Wrong Confirmation PIN", 2);
        }else if(name.equals("")){
            JOptionPane.showMessageDialog(null, "Name cannot be empty", "Empty Field", 2);
        }else if(!name.matches("[A-Z a-z]+")){
            JOptionPane.showMessageDialog(null, "Name cannot have digits or symbol", "Warning", 2);
        }else if(acc.equals("")){
            String str = jLabel8.getText().concat(" field cannot be empty");
            JOptionPane.showMessageDialog(null, str, "Empty field", 2);
        }else if(!acc.matches("[0-9.]+")){
            String str = jLabel8.getText().concat(" field must be a number");
            JOptionPane.showMessageDialog(null, str, "Warning", 2);
        }else if(deposit.equals("")){
            JOptionPane.showMessageDialog(null, "Deposit field cannot be empty", "Empty field", 2);
        }else if(!deposit.matches("[0-9.]+")){
            JOptionPane.showMessageDialog(null, "Deposit field must be a number", "Empty field", 2);
        }else{
            String accType = jComboBox1.getSelectedItem().toString();
            Double balance = Double.parseDouble(deposit);
            Double interestRate=0.0, creditLine=0.0, transFee=0.0;
            if(accType.equals("Saving Account")){
                interestRate=Double.parseDouble(acc);
            }else if(accType.equals("Credit Account")){
                creditLine=Double.parseDouble(acc);
            }else{
                transFee=Double.parseDouble(acc);
            }
            createAcc(pin, name, accType, balance, interestRate, creditLine, transFee);
//            createAcc(String name, String accType, Integer balance, Double interestRate, Double creditLine, Double transFee)
            jTable1.setModel(new DefaultTableModel(null, new Object[]{"Account Number", "Name", "Balance", "Account Type", "Creation Date"}));
            AccSearchOperations.fillTable(jTable1, "", sortByArg());
            setFieldAccSummary();
        }
    }//GEN-LAST:event_RegBtnMouseClicked

    private void jTextField_accTypeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_accTypeKeyTyped
        // TODO add your handling code here:
//        if(!Character.isDigit(evt.getKeyChar())){
//            evt.consume();
//        }
    }//GEN-LAST:event_jTextField_accTypeKeyTyped

    private void jTextField_depositFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_depositFocusGained
        // TODO add your handling code here:
        jTextField_deposit.setBorder(jLabelBorderAft);
    }//GEN-LAST:event_jTextField_depositFocusGained

    private void jTextField_depositFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_depositFocusLost
        // TODO add your handling code here:
        jTextField_deposit.setBorder(jLabelBorderBef);
    }//GEN-LAST:event_jTextField_depositFocusLost

    private void jTextField_depositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_depositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_depositActionPerformed

    private void jTextField_depositKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_depositKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_depositKeyPressed

    private void jTextField_depositKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_depositKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_depositKeyTyped

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        DerbyConn.shutConn();
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered

    }//GEN-LAST:event_jLabel10MouseEntered

    private void jTextField_totAccFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_totAccFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totAccFocusGained

    private void jTextField_totAccFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_totAccFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totAccFocusLost

    private void jTextField_totAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_totAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totAccActionPerformed

    private void jTextField_searchKeyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_searchKeyFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_searchKeyFocusGained

    private void jTextField_searchKeyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_searchKeyFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_searchKeyFocusLost

    private void jTextField_searchKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_searchKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_searchKeyActionPerformed

    private void jTextField_totSavingFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_totSavingFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totSavingFocusGained

    private void jTextField_totSavingFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_totSavingFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totSavingFocusLost

    private void jTextField_totSavingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_totSavingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totSavingActionPerformed

    private void jTextField_totCreditFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_totCreditFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totCreditFocusGained

    private void jTextField_totCreditFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_totCreditFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totCreditFocusLost

    private void jTextField_totCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_totCreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totCreditActionPerformed

    private void jTextField_totCheckingFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_totCheckingFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totCheckingFocusGained

    private void jTextField_totCheckingFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_totCheckingFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totCheckingFocusLost

    private void jTextField_totCheckingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_totCheckingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totCheckingActionPerformed

    private void jTextField_totBalanceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_totBalanceFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totBalanceFocusGained

    private void jTextField_totBalanceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_totBalanceFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totBalanceFocusLost

    private void jTextField_totBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_totBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totBalanceActionPerformed

    private void jTextField_totSaving1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_totSaving1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totSaving1FocusGained

    private void jTextField_totSaving1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_totSaving1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totSaving1FocusLost

    private void jTextField_totSaving1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_totSaving1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totSaving1ActionPerformed

    private void jTextField_totCredit1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_totCredit1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totCredit1FocusGained

    private void jTextField_totCredit1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_totCredit1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totCredit1FocusLost

    private void jTextField_totCredit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_totCredit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totCredit1ActionPerformed

    private void jTextField_totChecking1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_totChecking1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totChecking1FocusGained

    private void jTextField_totChecking1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_totChecking1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totChecking1FocusLost

    private void jTextField_totChecking1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_totChecking1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totChecking1ActionPerformed

    private void jTextField_AvgBalanceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_AvgBalanceFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AvgBalanceFocusGained

    private void jTextField_AvgBalanceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_AvgBalanceFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AvgBalanceFocusLost

    private void jTextField_AvgBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AvgBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AvgBalanceActionPerformed

    private void jTextField_searchKeyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchKeyKeyTyped
        // TODO add your handling code here:
        jTable1.setModel(new DefaultTableModel(null, new Object[]{"Account Number", "Name", "Balance", "Account Type", "Creation Date"})
        {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AccSearchOperations.fillTable(jTable1, jTextField_searchKey.getText(), sortByArg());
    }//GEN-LAST:event_jTextField_searchKeyKeyTyped

    private void jTextField_searchKeyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchKeyKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField_searchKeyKeyPressed

    private void jTextField_searchKeyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchKeyKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_searchKeyKeyReleased

    private void sortByComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByComboBoxActionPerformed
        // TODO add your handling code here:
        jTable1.setModel(new DefaultTableModel(null, new Object[]{"Account Number", "Name", "Balance", "Account Type", "Creation Date"})
        {
            boolean[] canEdit = new boolean [] {
            false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AccSearchOperations.fillTable(jTable1, jTextField_searchKey.getText(), sortByArg());
    }//GEN-LAST:event_sortByComboBoxActionPerformed

    private void filterBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterBtnMouseClicked
        // TODO add your handling code here:
        FilterWindow form = new FilterWindow();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
    }//GEN-LAST:event_filterBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClerkMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClerkMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClerkMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClerkMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClerkMainWindow().setVisible(true);
            }
        });
    }
    
    public void reset(){
        jPasswordField1.setText("");
        jPasswordField2.setText("");
        jTextField_Name.setText("");
        jComboBox1.setSelectedIndex(0);
        jTextField_accType.setText("");
        jTextField_deposit.setText("");
    }
    
    public void createAcc(String pin, String name, String accType, Double balance, Double interestRate, Double creditLine, Double transFee){
//        INSERT INTO accounts (`accNumb`,`name`, `accType`,`balance`,`interestRate`,`creditLine`,`transFee`) 
//        VALUES (10000001, "someone", "Saving Account", 500, 0.5, null, null);
        
        PreparedStatement st,st2;
        ResultSet rs,rs2;

        String query = "INSERT INTO users (USERTYPE, PASSWORD, \"NAME\", "
                    + "ACCTYPE, BALANCE, INTERESTRATE, CREDITLINE, TRANSFEE, DATECREATED)"
                    + " VALUES ('cust', ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)";
        try {
            st = DerbyConn.getConnection().prepareStatement(query);
            
            //Get the last accNumb on DB
//            st2 = DerbyConn.getConnection().prepareStatement("SELECT MAX(accNumb) accNumb FROM accounts");
//            rs2 = st2.executeQuery();
//            int accNumb = 0;
//            while(rs2.next()){
//                accNumb = rs2.getInt("accNumb")+1;
//            }
            


            st.setString(1, pin);
            
            st.setString(2, name);
            st.setString(3, accType);
            st.setDouble(4, balance);
            st.setDouble(5, interestRate);
            st.setDouble(6, creditLine);
            st.setDouble(7, transFee);
            
            st.executeUpdate();
            
            //Get Account Number
            st2 = DerbyConn.getConnection().prepareStatement("SELECT MAX(accNumb) accNumb FROM users");
            rs2 = st2.executeQuery();
            int accNumb = 0;
            while(rs2.next()){
                accNumb = rs2.getInt("accNumb");
            }
            
            TransactionOp.createTable(accNumb);
            
            JOptionPane.showMessageDialog(null, "New account with Account Number "+accNumb+" is created", "Account created", 1);
            reset();
            System.out.println("New Account Created");
            
            
            
        }catch (SQLException ex) {
//            Logger.getLogger(LoginWindow.class.getName()).log(Level.SEVERE, null, ex);
              System.out.println(ex);
              JOptionPane.showMessageDialog(null, ex,"Register Failed",2);
        }
        
       
    }
    
    public String sortByArg(){
        String arg="";
        if(sortByComboBox.getSelectedItem()== "Account Number"){
            arg="accNumb";
        }else if(sortByComboBox.getSelectedItem()== "Name"){
            arg="name";
        }else if(sortByComboBox.getSelectedItem()== "Balance"){
            arg="balance";
        }else if(sortByComboBox.getSelectedItem()== "Account Type"){
            arg="accType";
        }else{
            arg="dateCreated";
        }
        return arg;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel APY_CreditLine_Transfee_Panel;
    private javax.swing.JPanel AccType_Panel;
    private javax.swing.JTabbedPane AllSummaryTab;
    private javax.swing.JPanel ConfPIN_Panel;
    private javax.swing.JPanel DepositPanel;
    private javax.swing.JPanel NamePanel;
    private javax.swing.JPanel PIN_Panel;
    private javax.swing.JButton RegBtn;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JPanel SearchAccountsPanel;
    private javax.swing.JPanel accInfoPanel;
    private javax.swing.JPanel createAccPanel;
    private javax.swing.JLabel filterBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_AvgBalance;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_accType;
    private javax.swing.JTextField jTextField_deposit;
    private javax.swing.JTextField jTextField_searchKey;
    private javax.swing.JTextField jTextField_totAcc;
    private javax.swing.JTextField jTextField_totBalance;
    private javax.swing.JTextField jTextField_totChecking;
    private javax.swing.JTextField jTextField_totChecking1;
    private javax.swing.JTextField jTextField_totCredit;
    private javax.swing.JTextField jTextField_totCredit1;
    private javax.swing.JTextField jTextField_totSaving;
    private javax.swing.JTextField jTextField_totSaving1;
    private javax.swing.JLabel searchBtn;
    private javax.swing.JComboBox<String> sortByComboBox;
    private javax.swing.JPanel summaryTabTemp;
    // End of variables declaration//GEN-END:variables
}
